---
- name: Ensure Grafana Agent service unit is applied
  ansible.builtin.template:
    src: grafana-agent.service.j2
    dest: /etc/systemd/system/grafana-agent.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Grafana Agent

- name: Ensure Grafana Agent service is enabled and started
  ansible.builtin.systemd:
    name: grafana-agent.service
    state: started
    enabled: true
    daemon_reload: true
