---
- name: Restart Grafana Agent
  ansible.builtin.systemd:
    name: grafana-agent.service
    state: restarted
    daemon_reload: true

- name: Reload Grafana Agent
  ansible.builtin.systemd:
    name: grafana-agent.service
    state: reloaded
